---

- name: 发布到测试环境
  hosts: test
  serial: 1
  roles:
    - role: build
    - role: docker
    - role: cleanup


- name: 发布到生产环境
  hosts: prod
  serial: 1
  roles:
    - role: build
    - role: docker
    - role: cleanup